### ISSUE TITLE
Date converter not working in 2.5.1(308)

### ISSUE THREAD

**Issue by losterberg** [mjball/Date-Alfred#1]
![image](https://cloud.githubusercontent.com/assets/9434556/4811157/7c8c8cae-5eb8-11e4-805c-25fe36f112cd.png)

I have also upgraded to Yosemite, but main issue seems to be Alfred version (colleague still on mavericks with same problem).

**Comment by mjball** [comment]
I'm on 2.5.1 with Mavericks as well and have no issues.

![image](https://cloud.githubusercontent.com/assets/378111/4811229/f589137a-5eb8-11e4-9a74-1693baa931b0.png)
- Can you provide steps to reproduce the problem?
- Do you have [the necessary software installed?](https://github.com/mjball/Date-Alfred#requirements)
- What version of node are you using?
- What happens if you fire up `node` and run the following snippet?

``` javascript
var d = new Date();
require("util").format("%d/%d/%d %d:%s:%s.%d", d.getMonth()+1, d.getDate(), d.getFullYear(), d.getHours(), (d.getMinutes() < 10 ? "0" : "") + d.getMinutes(), (d.getSeconds() < 10 ? "0" : "") + d.getSeconds(), d.getMilliseconds());
```

**Comment by losterberg** [comment]
My bad - Yosemite install cleaned out my node.js so I just had to do a reinstall. Most likely a similar node issue with Mavericks colleague, will troubleshoot some more and get back to you. Sorry for false alarm.

**Comment by javi7** [comment]
I'm the colleague :-). I'm running node v0.10.29, alfred v2.5.1 on Mavericks

When I run that node snippet I get:
'10/28/2014 14:48:00.898'

But when I use Alfred I get:
![image](https://cloud.githubusercontent.com/assets/2027972/4814922/0a399a82-5ed3-11e4-9560-b4f7ca6f1c34.png)

**Comment by mjball** [comment]
Please try this version and send me a screenshot. https://s3.amazonaws.com/uploads.hipchat.com/10819/179106/XlXVB8XgmHp4uFE/Date-debug.alfredworkflow

**Comment by javi7** [comment]
![image](https://cloud.githubusercontent.com/assets/2027972/4816062/340cb6c4-5edc-11e4-9b8c-80dcb84b0313.png)

**Comment by mjball** [comment]
Are you sure that node is in the path of whichever shell the script filter uses?

Pull up the "Workflows" tab in Alfred preferences, select Date (or Date-debug), double-click the "Script Filter" and take a look at the "Language" dropdown. If it's zsh, do you actually have zsh, and is `node` in the path?

![image](https://cloud.githubusercontent.com/assets/378111/4816209/8dc7966a-5edd-11e4-8c1c-587ec760d7c5.png)

![image](https://cloud.githubusercontent.com/assets/378111/4816217/9424ea6c-5edd-11e4-8986-48e4fef916b6.png)

**Comment by mjball** [comment]
@losterberg did reinstalling node fix your flavor of the problem?

**Comment by losterberg** [comment]
Yeah it did - sorry if that wasn't clear from my comment.

**Comment by javi7** [comment]
My language was set to zsh, which is installed and has node on its path. I tried switching to bash to no avail.
